spring:
  profiles:
    active: local
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${JWT_SECRET:v6yB8eN2pL5fX9zW1qR4tG7hJ0kM3nB6v9yB8eN2pL5fX9zW1qR4tG7hJ0kM3nB6}
  issuer: ${JWT_ISSUER:finvibe-user}
  access-token-expiration: 3600000 # 1 hour
  refresh-token-expiration: 1209600000 # 14 days

app:
  oauth2:
    base-url: ${OAUTH_REDIRECT_URL:http://localhost:3000/oauth/callback}
